### ISSUE TITLE
curiosity question: Progress?

### ISSUE THREAD

**Issue by loneicewolf** [KaptianCore/Cyber-Tools#1]
any progress? 

also, what specifically do the readme' file mean with `hash generator` ? I know what a hash is, but "hash generator" - care to elaborate? `:)`

Or do you maybe mean a program that generates hashes based on the inputs? I probably misunderstood (which is the 2nd reason of this issue ).

Wishes from Sweden!

**Comment by KaptianCore** [comment]
Hey this is something I will work on when I have the time sorry so it may stay in this state for a while.

**Comment by loneicewolf** [comment]
> Hey this is something I will work on when I have the time sorry so it may stay in this state for a while.

Oh, I see! No rush!  and all the best with it 🚀
